### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by Capps0611** [johnnyguitarFP/deadmatterdedisetup#10]
When adding players steam64 ID to the whitelist using the below code in the Game.ini, the whitelist isn't actually updating. I can confirm that enabling the whitelist is working. But whenever you add in the IDs they are not being allowed through.

[/Script/DeadMatter.SurvivalBaseGamemode]
WhitelistActive=true (**this part work**)
+Whitelist=STEAM64ID (**this part doesn't work**)

**Comment by Khurune** [comment]
Can you try removing the prefixed + for me

**Comment by Capps0611** [comment]
Sure thing, when I remove the + it completely removes the entire line so it would look like this on start

(**Before Server Start**)
[/Script/DeadMatter.SurvivalBaseGamemode]
WhitelistActive=true
Whitelist=STEAM64ID

(**After Server Start**)
[/Script/DeadMatter.SurvivalBaseGamemode]
WhitelistActive=true

**Comment by Capps0611** [comment]
Further testing it looks like when users connect to the server their steam ID isn't being pulled at all, which explains why the Whitelist and why admin aren't working. There is no way for the server to tell that you are supposed to be there or be an admin as it can't pull your Steam 64 ID.

![image](https://user-images.githubusercontent.com/16946574/91073265-cce66700-e608-11ea-8650-4c886eb04377.png)

**Comment by Capps0611** [comment]
Further testing it looks like when users connect to the server their steam ID isn't being pulled at all, which explains why the Whitelist and why admin aren't working. There is no way for the server to tell that you are supposed to be there or be an admin as it can't pull your Steam 64 ID.

**Comment by Capps0611** [comment]
So after doing some more extensive testing we have found the following will allow you to use the whitelist on your server.

In the below example if you remove **Whitelist=DONOTREMOVE** every time you start the server all other whitelist variables will be removed from the Game.ini and those whitelisted will only remain whitelisted until the server restarts.

[/Script/DeadMatter.SurvivalBaseGamemode]
WhitelistActive=true
Whitelist=DONOTREMOVE 
Whitelist=Steam64ID
Whitelist=Steam64ID

**Comment by humangenome** [comment]
Also the +Whitelist= do not work, they just boot every player back to the Main Menu

**Comment by johnnyguitarFP** [comment]
This is a known issue and will be addressed ASAP, I’ve sent it over to the team.
