### ISSUE TITLE
OnlineSubsystemSteam Being removed from config on start

### ISSUE THREAD

**Issue by Khurune** [johnnyguitarFP/deadmatterdedisetup#12]
TCAdmin platform.

Any time I add 
[OnlineSubsystemSteam]
GameServerQueryPort=X

To the engine.ini it's being removed on start causing the server not to show up. Any Ideas? I've also tried using -GameServerQueryPort= on the command line.

Warning: OSS: TryLoadSubsystemAndSetDefault: LoadSubsystemModule([Steam]) failed
[deadmatter (3).log](https://github.com/johnnyguitarFP/deadmatterdedisetup/files/5119476/deadmatter.3.log)

**Comment by juanhaywood** [comment]
Did you also add the following to game.ini? It needs both config file changes:

[/Script/deadmatter.ServerInfoProxy]
SteamQueryPort=X

**Comment by Khurune** [comment]
Yea, done both. Weird thing is the exact setup works fine on my PC when testing, but moving onto the nodes with the TCA backend removes it, the only difference I can really see in the logs is the PC is calling steamAPI without issues where as on the nodes it's not. I'm going to test on my PC with steam removed and only using steamCMD. 
Will update once I've had time to see if that could be an issue.

**Comment by Khurune** [comment]
Update, this only seems to happen when using port 27016, any other port this doesn't happen with.

I've run into another blocker, and will make a new issue for that after some more testing.
