### ISSUE TITLE
connection to linux server failed

### ISSUE THREAD

**Issue by kwinkel** [johnnyguitarFP/deadmatterdedisetup#13]
When using the linux server files, I can not connect to the server; related server log output:
```
[2020.08.24-17.41.25:321][893]LogNet: NotifyAcceptingConnection accepted from: <myip>:58966
[2020.08.24-17.41.25:321][893]LogHandshake: IncomingConnectionless: Error reading handshake packet.
--- same message repeated ---
```

Same for different players.
Server installed with steamcmd @ Debian

Complete log:
[server.log](https://github.com/johnnyguitarFP/deadmatterdedisetup/files/5119410/serverlog.log)

**Comment by kwinkel** [comment]
provided docker image for fast reproduction https://hub.docker.com/repository/docker/inttheory/deadmatter-server

**Comment by johnnyguitarFP** [comment]
Linux is not currently supported and those files are out of date.
