### ISSUE TITLE
QueryPort unchangeable 

### ISSUE THREAD

**Issue by Capps0611** [johnnyguitarFP/deadmatterdedisetup#3]
I have attempted to change the query port in Engine.ini as well as via the launch parameters to no avail. The server continues to default to 27016.

Parameters used/tried:

- QueryPort (based on the tags, this should be the variable to change the port)
- SteamQueryPort
- GameServerQueryPort
- ServerPort
- SteamPort

**Comment by Khurune** [comment]
Can also confirm this, please allow us some way of changing this. I've tried from command line and a few ini files without luck.
Also need to do more testing on multihome, but that seems to not work as well.

**Comment by humangenome** [comment]
Confirmed on our end too

**Comment by johnnyguitarFP** [comment]
See the examples.

**Comment by Capps0611** [comment]
What examples? The only example you have on the github is to change the GAME port and that is not the issue. The issue lies with the QUERY Port which appears to be hard coded to 27016 which results in this value not being able to be changed. The query port used by steam needs to be a changeable port not a hard coded value. Please do not just lock and close this issue without fully reading through it. I understand you guys are slammed with the launch, but this is an issue that needs to be addressed as it pertains to your dedicated server structure.

**Comment by Capps0611** [comment]
What examples? The only example you have on the github is to change the GAME port and that is not the issue. The issue lies with the QUERY Port which appears to be hard coded to 27016 which results in this value not being able to be changed. The query port used by steam needs to be a changeable port not a hard coded value. Please do not just lock and close this issue without fully reading through it. I understand you guys are slammed with the launch, but this is an issue that needs to be addressed as it pertains to your dedicated server structure.

**Comment by johnnyguitarFP** [comment]
https://github.com/johnnyguitarFP/deadmatterdedisetup/blob/master/Game.ini

Line 7

https://github.com/johnnyguitarFP/deadmatterdedisetup/blob/master/Engine.ini

Line 4

**Comment by humangenome** [comment]
You the man, thanks!!

Ryan Pennington

**Comment by Capps0611** [comment]
Thank you for the edit, I see those examples were added about 20 minutes ago, so thank you for getting them added. We will try them out now
