### ISSUE TITLE
Unable to see the server

### ISSUE THREAD

**Issue by ibejoeyz** [johnnyguitarFP/deadmatterdedisetup#4]
I had the server running with the Dedicated server setup. I ran it for a little while and turned it off to change a few things and now it won't show up. Is there something I have wrong here? This is my game.ini

[/Script/Engine.GameSession]
MaxPlayers=36

[/Script/DeadMatter.SurvivalBaseGameState]
ServerName=The Aftermath
+ServerTags=KOS
MOTD=Welcome to The Aftermath.

**Comment by johnnyguitarFP** [comment]
Check the looks and look for Steam API Initialization, post the results here.
