### ISSUE TITLE
Query Port (not Port) is hard set to 27016

### ISSUE THREAD

**Issue by humangenome** [johnnyguitarFP/deadmatterdedisetup#5]
Both issues were just closed but the issue is not resolved.

The Steam Query Port cannot be changed. It's hard locked to 27016.

Game port can be changed as the examples show. The problem is the query port (what server list and connecting clients use) is hard coded to 27016. This means you can't create more than one game server on a single machine (problem for GSPs or people with high performance nodes)

**Comment by humangenome** [comment]
You can see by checking resource monitor open ports. -QueryPort appears to work in launch param but it is still also opening 27016 every time.

**Comment by johnnyguitarFP** [comment]
The Query port is not hard locked to 27016, you can check the examples to see how to change the Query port. This is the same method I use for the official servers and should allow you to host multiple servers on the same box.

**Comment by humangenome** [comment]
Right. It may show in the server list but it is not queryable (cannot fetch
information about the server)

They overlap 27016. You can check two or more game servers that are running
on the same box and see 27016 in the list of open ports.

To fetch server information via Steam query it would need to be adjustable
off of 27016. I am sure there are other unmentioned things dependent on a
unique Steam Query Port.

Ryan Pennington
